IMPLICITAUTSTART=false
LANGUAGE=Python
OBJECTMAPSTYLE=script
TEST_CASES=tst_textbox tst_button tst_checkbox tst_radio_button tst_dropdown tst_links tst_table tst_dynamic_table tst_alert tst_file_upload tst_mouse_actions tst_keyboard_actions tst_new_window tst_frame tst_property_verification tst_data_driven_login tst_Script tst_variables tst_ifcondition tst_loops tst_ExceptionHandling tst_ReusbaleFunction tst_propertyverf tst_Assertions tst_Screenshot tst_Table1 tst_log tst_Results tst_DEbug tst_sync
WRAPPERS=Web
